# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get -qq update
      sudo apt-get -qq install g++-4.8 g++-multilib
      export CXX=g++-4.8
      npm i
    displayName: 'Install dependencies and build'
  - script: |
      npx prebuild --all -u $GITHUB_RELEASE_TOKEN
      npx prebuild --all -a ia32 -u $GITHUB_RELEASE_TOKEN
    env:
      GITHUB_RELEASE_TOKEN: $(GITHUB_RELEASE_TOKEN)
    displayName: 'Prebuild and publish'
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm i
    displayName: 'Install dependencies and build'
  - script: |
      npx prebuild --all -u $GITHUB_RELEASE_TOKEN
    env:
      GITHUB_RELEASE_TOKEN: $(GITHUB_RELEASE_TOKEN)
    displayName: 'Prebuild and publish'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - script: |
      npm i
    displayName: 'Install dependencies and build'
  - script: |
      npm config set msvs_version 2017
    displayName: 'Use MSVC 2017'
  - script: |
      npx prebuild --all --include-regex "\.(node|exe|dll|pdb)$" -u %GITHUB_RELEASE_TOKEN%
      npx prebuild --all -a ia32 --include-regex "\.(node|exe|dll|pdb)$" -u %GITHUB_RELEASE_TOKEN%
    env:
      GITHUB_RELEASE_TOKEN: $(GITHUB_RELEASE_TOKEN)
    displayName: 'Prebuild and publish'
